#! /usr/bin/env python

import argparse

parser = argparse.ArgumentParser(prog = "genomon_summary")

parser.add_argument("--version", action = "version", version = "genomon_summary-2.0.0")
parser.add_argument('analysis_type', choices=['wgs', 'exome'], help = "analysis type")
parser.add_argument("sample_list_file", help = "input sample list flie [csv/tsv/xlsx]", type = str)
parser.add_argument("project_root", metavar = "project_root_dir", help = "output root directory", type = str)
parser.add_argument("genomon_conf_file", help = "config file for genomon pipeline", type = str)
parser.add_argument("task_conf_file", help = "parameter file for genomon pipeline", type = str)
                    
args = parser.parse_args()

import os
args.project_root = os.path.abspath(args.project_root)

from genomon_summary.run import *

main(args)
